### ISSUE TITLE
コマンド実行時のエラーについて

### ISSUE THREAD

**Issue by ghost** [gamesukimanIRS/xyzplugin#2]
**コマンド実行時のエラー文**:
`Error: "Call to a member function getFolderName() on null" (EXCEPTION) in "/plugins/xyzplugin-master/src/xyzplugin/Main" at line 28`
(何もない変数($level)で関数を実行しようとしています)

**原因**:
`Notice: Undefined variable: level in \plugins\xyzplugin-master\src\xyzplugin\Main.php on line 28`
(28行目の $level 変数が未定義ですよ)

**修正前**:
```php
if($sender instanceof Player){
        $sender->getName();
        $level->getFolderName();
        $l = $sender->getLevel();
        $x = $sender->getX();
　　 # 続く...
```

**修正後**:
```php
if($sender instanceof Player){
        $sender->getName();
        $level = $sender->getLevel();// $levelオブジェクトを定義
        $l = $level->getFolderName(); // levelオブジェクトから取得して$lに代入
        $x = $sender->getX();
　　 # 続く...
```

**ちなみに**:
これを修正した後コマンドを実行すると、使用状況: /xyz と出るが、
```php
$sender->sendMessage("§b[XYZ]§fあなたの座標はX=".$x."、Y=".$y."、Z=".$z."、ワールド=".$l."です。");
```
の後に
```php
return true;
```
と入れると出なくなる(コマンドを正常に処理できましたよーという証)。
このreturn trueの後のコードは実行されないので注意。

**Comment by gamesukimanIRS** [comment]
ふむふむ。returnは正直意味分からなくて入れてませんでしたが、入れないとこうなるのですね。

$levelの修正を始めありがとうございます！

**Comment by gamesukimanIRS** [comment]
すみませぬ……

それ書いたのにgetLevel()ないですって言う返答が返ってくるんですな……

**Comment by ghost** [comment]
修正後の文にしてくださいな

**Comment by gamesukimanIRS** [comment]
どうやらサーバー再起動ではなくサーバーリロードにしてたのが原因の模様

手違いです(*_ _)人ｺﾞﾒﾝﾅｻｲ
